### PR TITLE
Update cave arena

### PR DESCRIPTION
**Pull request by Agoichi**
## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by TheShuEd** [comment]
image
wrong side

**Comment by Agoichi** [comment]
> image
> 
> please no
Ahahahaha. FUCK. This is old version. New one i deleted)

**Comment by Agoichi** [comment]
Mkay. Well. Fuck. Let me see if i still have newer version of cave

**Review by TheShuEd — CHANGES_REQUESTED** [review]
waiting map update

**Comment by Agoichi** [comment]
Так а чё не так я так и не понял.
Я буду звонить в полицию.

**Pull request closed without merging**
