### PR TITLE
add brass door

### PR DESCRIPTION
**Pull request by Jaraten**
added brass door with modifierset:"FlimsyMetallic"

### CODE REVIEW

**Comment by TheShuEd** [comment]
do you test this door in game?
image

the sprite in the open state doesn't look right, compare it to the wooden one

**Comment by TheShuEd** [comment]
Also there is a lot of duplication of components in yml, it is worth to make a common parent for all doors, where all duplications should be placed.

**Comment by TheShuEd** [comment]
oh, I get it, it's a door going down. In that case, you need the correct sounds.

**Comment by Jaraten** [comment]
I don't understand where you got that sprit
Снимок экрана 2024-05-22 181455
e from. About the yml, I just copied an existing wooden one.

**Review by TheShuEd — CHANGES_REQUESTED** [review]
Also there is a lot of duplication of components in yml, it is worth to make a generic parent for all doors, where all duplications should be placed.

**Pull request closed without merging**
